const runes = [
  { 'num': 1,  'name': 'Blood',                     'stats': '- Strength/Magic +1500',                                                          'value': 0.07850 },
  { 'num': 2,  'name': 'Steel',                     'stats': '- Stamina +1500',                                                                 'value': 0.00000 },
  { 'num': 3,  'name': 'Fortune',                   'stats': '- Luck +1500',                                                                    'value': 0.00000 },
  { 'num': 4,  'name': 'Oath',                      'stats': '- Quest Reward +20%\n- Option Rate +500',                                         'value': 0.00000 },
  { 'num': 5,  'name': 'Rage',                      'stats': '- Attack/Elemental Intensity +70',                                                'value': 0.37293 },
  { 'num': 6,  'name': 'Blessing',                  'stats': '- Ely Gain Rate +50',                                                             'value': 0.00000 },
  { 'num': 7,  'name': 'Devotion',                  'stats': '- Minimum Damage +50',                                                            'value': 0.50727 },
  { 'num': 8,  'name': 'Wealth',                    'stats': '- Item Drop Rate +20',                                                            'value': 0.00000 },
  { 'num': 9,  'name': 'Destruction',               'stats': '- Maximum Damage +50',                                                            'value': 0.47698 },
  { 'num': 10, 'name': 'Wisdom',                    'stats': '- Craft Rate +5',                                                                 'value': 0.00000 },
  { 'num': 11, 'name': 'Ruin',                      'stats': '- Critical Damage +50',                                                           'value': 0.83925 },
  { 'num': 12, 'name': 'Trust',                     'stats': '- Accuracy +10',                                                                  'value': 0.00000 },
  { 'num': 13, 'name': 'Passion',                   'stats': '- Static Damage +1500',                                                           'value': 0.02413 },
  { 'num': 14, 'name': 'Perseverance',              'stats': '- EXP Gain Rate +10.0',                                                           'value': 0.00000 },
  { 'num': 15, 'name': 'Wrath',                     'stats': '- Attack/Elemental Intensity +5%',                                                'value': 0.55744 },
  { 'num': 16, 'name': 'Mania',                     'stats': '- Static Damage +8%',                                                             'value': 0.27303 },
  { 'num': 17, 'name': 'Life',                      'stats': '- Maximum HP +5%',                                                                'value': 0.00000 },
  { 'num': 18, 'name': 'Peace',                     'stats': '- Basic Stats +1500',                                                             'value': 0.07850 },
  { 'num': 19, 'name': 'Harmony',                   'stats': '- Basic Stats +5%',                                                               'value': 0.45058 },
  { 'num': 20, 'name': 'Insight',                   'stats': '- Defense Penetration +10\n- Cooldown Reduction by 1s at 0.1% chance per strike', 'value': 0.00000 },
  { 'num': 21, 'name': 'Peace and Harmony',         'stats': '- Basic Stats +1500\n- Basic Stats +5%',                                          'value': 0.52981 },
  { 'num': 22, 'name': 'Passion and Rage',          'stats': '- Static Damage +1500\n- Attack/Elemental Intensity +70',                         'value': 0.39706 },
  { 'num': 23, 'name': 'Steel and Life',            'stats': '- Stamina +1500\n- Maximum HP +5%',                                               'value': 0.00000 },
  { 'num': 24, 'name': 'Perseverance and Oath',     'stats': '- EXP Gain Rate +10.0\n- Quest Reward +30%',                                      'value': 0.00000 },
  { 'num': 25, 'name': 'Mania and Wrath',           'stats': '- Static Damage +8%\n- Attack/Elemental Intensity +5%',                           'value': 0.83048 },
  { 'num': 26, 'name': 'Devotion and Destruction',  'stats': '- Damage +50',                                                                    'value': 0.98425 },
  { 'num': 27, 'name': 'Blessing and Wealth',       'stats': '- Ely Gain Rate +50\n- Item Drop Rate +20',                                       'value': 0.00000 },
  { 'num': 28, 'name': 'Nature and Dominance',      'stats': '- Normal Added Damage +6000\n- Normal Damage Amplification +3%',                  'value': 0.95916 },
  { 'num': 29, 'name': 'Fear and Death',            'stats': '- Boss Added Damage +10000\n- Boss Damage Amplification +5%',                     'value': 1.62997 },
  { 'num': 30, 'name': 'Ruin and Corruption',       'stats': '- Critical Damage +50\n- Critical Rate +1',                                       'value': 0.83925 },
]

export default runes;